### ISSUE TITLE
Converting `.SetMeta` output to JSON

### ISSUE THREAD

**Issue by maggie44** [samber/slog-gin#14]
Thanks for this slog/Gin library. Great combo.

I have started using it with Golang Gin's `.SetMeta()` method on `c.Error`:

```
_ = c.Error(fmt.Errorf("etresdf")).SetMeta("test12345")
```

When it logs the output it is malformed: 

```
{"time":"2024-01-19T20:28:45.497692Z","level":"ERROR","msg":"Error #01: etresdf\n     Meta: test12345\n",
```

Here is the default output with Logrus:

```
8:38PM ERR Error #01: etresdf
     Meta: test12345
 ip=127.0.0.1 latency=0.246416 method=GET path=/ping status=500 user_agent=PostmanRuntime/7.33.0
```

Not sure how much can be done about it.

**Comment by samber** [comment]
Hi @maggie44 

Sorry for asking this, but what is the difference according to you?

I suppose if you use the slog-gin + slog.TextHandler, you will get pretty much the same result.

**Comment by maggie44** [comment]
A very valid point. I’m not sure what’s possible as I haven’t look at the code. Ideally though `Meta` would be a (lowercase) key so that meta data could be referenced in JSON. 

I don’t know how that compares to some of the Logrus JSON implementations but as slog has JSON options built in if it’s doable then I think it would be a nice way to render it.

**Comment by samber** [comment]
This is related to the way gin is implemented. `err.Error()` outputs a string containing both error message and meta. slog-gin and logrus have the same behavior.

I'm closing this issue. Feel free to open it again if you think we need more discussion on it!
