### ISSUE TITLE
无法获取请求中的body信息

### ISSUE THREAD

**Issue by EddyLee1010** [samber/slog-gin#18]
`func newBodyReader(reader io.ReadCloser, maxSize int, recordBody bool) *bodyReader {
	var body *bytes.Buffer
	if recordBody {
		body = bytes.NewBufferString("")
	}
	return &bodyReader{
		ReadCloser: reader,
		body:       body,
		maxSize:    maxSize,
		bytes:      0,
	}
}`

感觉这里没有给body赋值呢。

**Comment by samber** [comment]
What parameters did you inject in `sloggin.NewWithConfig(...)` ?

**Comment by EddyLee1010** [comment]
> What parameters did you inject in `sloggin.NewWithConfig(...)` ?

thanks goodman.  I forget inject 'withrequestbody:true'
