### ISSUE TITLE
Allow parsing of latency in desired unit

### ISSUE THREAD

**Issue by manish-baghel** [samber/slog-gin#21]
https://github.com/samber/slog-gin/blob/3f56650b1e9cfe502d84e6deb38c501ba3201389/middleware.go#L164

In the above code, I'd like to either override the value or to use an option to parse latency in desired unit for eg. ms.
This can be acheived using methods like https://pkg.go.dev/time#Duration.Milliseconds, https://pkg.go.dev/time#Duration.Microseconds, etc.

Or a simpler option for using https://pkg.go.dev/time#Duration.String to return latency in string format

**Comment by samber** [comment]
What slog handler do you use?

Can you add a `ReplaceAttr` formatter?

I'm not against your proposal, but I'm not sure it is in the scope of this library to handle such customization.

**Comment by samber** [comment]
You can also use https://github.com/samber/slog-formatter

**Comment by manish-baghel** [comment]
@samber 
Thanks for your response and sorry for my delayed reply.

For reference, this works
```go
logger := slog.New(
	slogformatter.NewFormatterHandler(
		slogformatter.FormatByKind(slog.KindDuration, func(v slog.Value) slog.Value {
			return slog.Float64Value(float64(v.Duration().Microseconds()) / 1000) // ms with float precision
		}),
	)(
		slog.NewJSONHandler(os.Stdout, nil),
	),
)
	
router := gin.New()
router.Use(sloggin.New(logger))
router.Use(gin.Recovery())
```
