### ISSUE TITLE
Need a Otel standard example

### ISSUE THREAD

**Issue by Fleezesd** [samber/slog-gin#22]
Opentelemetry is quite intrusive for Go.Please give a standardized example of Gin for reference，Thank you.

**Comment by samber** [comment]
An example of both Gin, slog and OTEL in a single project ?

**Comment by Fleezesd** [comment]
yes, I use otelgin.middleware with slog-gin，but log not has span and traceId, I see slog-multi make baseAttributes to store the otel message
