### ISSUE TITLE
Config option to exclude routes

### ISSUE THREAD

**Issue by bmeverett** [samber/slog-gin#3]
I'm setting up this middleware globally and want to be able to exclude routes so they don't get logged. Would you consider adding a config option like `ignoreRoutes` so that if a url path is in the `ignoreRoutes` then it doesn't get logged?

**Comment by samber** [comment]
We can imagine something like:

```
router.Use(
    sloggin.New(
        logger,
        slogging.Ignore(func (c *gin.Context) bool {
            return false
        }),
    ),
)
```

This could be declined with the following syntax: [Prefix][Entity][Suffix]

With:
- Prefix: Accept/Ignore (or Take/Drop/Skip)
- Entity: 0̸/URL/Host/Method/Header
- Suffix: 0̸/Regexp/Prefix/Suffix

Example:
- Accept(func (c *gin.Context) bool { ... })
- IgnoreURLMatch("^/v1/(.*)$")
- AcceptMethod(http.Post, http.Get, ...)
- IgnoreHostSuffix(".acme.org")

WDYT?

**Comment by bmeverett** [comment]
I think this looks great and even more then I was expecting! 

So if I'm understanding and I want to exclude `/test` I would do something like 

```
router.Use(
    sloggin.New(
        logger,
        slogging.IgnoreURLMatch("/test")
    ),
)
```

**Comment by samber** [comment]
For the "Match" operation, I would propose `slogging.IgnoreURLMatch(regexp.MustCompile( ... ))`

Your example would be `slogging.IgnoreURLContains("/test")` or `slogging.IgnoreURLHasPrefix("/test")`

**Comment by bmeverett** [comment]
Sounds good!

**Comment by samber** [comment]
done

**Comment by bmeverett** [comment]
Thank you! 🙌
