### ISSUE TITLE
access logger

### ISSUE THREAD

**Issue by erwiese** [samber/slog-gin#33]
Hi,
what is the best way to access the logger instance from my handler functions?
Any way to access it via *gin.Context ?
To set as default with  `slog.SetDefault(logger)` is not sufficient.

Thanks

**Comment by samber** [comment]
I'm not sure this is a question related to `slog-gin`.

Example:

```go
logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

router := gin.New()

router.Use(sloggin.New(logger))
router.Use(gin.Recovery())

router.GET("/ping", func(c *gin.Context) {
    logger.Info("hello world")
    c.String(http.StatusOK, "pong")
})
```

**Comment by erwiese** [comment]
Indeed this is not restricted to slog-gin. As my handlers are in a dedicated package, there is no access to the logger instance.
